In [1]:
from keras.applications import VGG16

# Load the VGG16 model without the top (fully connected layers)
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5
58889256/58889256 [==============================] - 0s 0us/step

In [2]:
for layer in base_model.layers:
    layer.trainable = False

In [3]:
from keras.models import Model
from keras.layers import Flatten, Dense

# Add custom regression layers on top of VGG16
x = base_model.output
x = Flatten()(x)
x = Dense(1024, activation='relu')(x)
output = Dense(1, activation='linear')(x)  # Output layer for regression, adjust units for your task

# Create a new model
model = Model(inputs=base_model.input, outputs=output)

In [4]:
model.compile(optimizer='adam', loss='mean_squared_error')

# Data creation

In [1]:
import pandas as pd
import os
import csv
import requests
import time

In [2]:
# Load df
df = pd.read_csv("/notebooks/sample_products.csv")

In [3]:
# Get ids and urls and zip them
ids = df.id.values.tolist()
urls = df.image_url.values.tolist()
all_values = list(zip(ids, urls))

In [4]:
# Function to download images



def image_extractor(ids_and_images_url):
    # Check if images folder exists, if not create it
    if not os.path.exists('images'):
        os.makedirs('images')

    # Create a CSV file to store image names and IDs
    csv_file_path = 'images/images.csv'
    with open(csv_file_path, 'w', newline='') as csvfile:
        fieldnames = ['id', 'image_name']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()

        total_images_downloaded = 0

        # Download the images using the requests library
        for id, image_url in ids_and_images_url:
            # Strip leading and trailing whitespace from the URL
            image_url = image_url.strip()

            try:
                headers = {
                          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
                          }
                response = requests.get(image_url, timeout=1, headers=headers)
                response.raise_for_status()

                # Check if the request was successful
                if response.status_code == 200:
                    # Save the image to a file
                    img_file = f'{id}.jpg'
                    with open(f'images/{img_file}', 'wb') as f:
                        f.write(response.content)

                    # Write image name and ID to CSV
                    writer.writerow({'id': id, 'image_name': img_file})
                    total_images_downloaded += 1

                    # Print progress
                    print(f"Downloaded {total_images_downloaded} images")

            except (requests.exceptions.RequestException, ConnectionError) as e:
                print(f"Connection error encountered for ID {id}: {e}")

            # Add a small delay between requests to avoid overwhelming the server
            time.sleep(0.5)

    print("Download process completed.")

## image downloading process has some errors. Get the output of the image extractor and locate the mages with errors for data pre-processing.

In [9]:
# Extract images into images folder
image_extractor(all_values)

Downloaded 1 images
Downloaded 2 images
Downloaded 3 images
Downloaded 4 images
Downloaded 5 images
Downloaded 6 images
Downloaded 7 images
Downloaded 8 images
Downloaded 9 images
Downloaded 10 images
Downloaded 11 images
Downloaded 12 images
Downloaded 13 images
Downloaded 14 images
Downloaded 15 images
Downloaded 16 images
Downloaded 17 images
Downloaded 18 images
Downloaded 19 images
Downloaded 20 images
Downloaded 21 images
Downloaded 22 images
Downloaded 23 images
Downloaded 24 images
Downloaded 25 images
Downloaded 26 images
Downloaded 27 images
Downloaded 28 images
Downloaded 29 images
Downloaded 30 images
Downloaded 31 images
Downloaded 32 images
Downloaded 33 images
Downloaded 34 images
Downloaded 35 images
Downloaded 36 images
Downloaded 37 images
Downloaded 38 images
Downloaded 39 images
Downloaded 40 images
Downloaded 41 images
Downloaded 42 images
Downloaded 43 images
Downloaded 44 images
Downloaded 45 images
Downloaded 46 images
Downloaded 47 images
Downloaded 48 images
Downloaded 49 images
Downloaded 50 images
Downloaded 51 images
Downloaded 52 images
Downloaded 53 images
Downloaded 54 images
Downloaded 55 images
Downloaded 56 images
Downloaded 57 images
Downloaded 58 images
Downloaded 59 images
Downloaded 60 images
Downloaded 61 images
Downloaded 62 images
Downloaded 63 images
Downloaded 64 images
Downloaded 65 images
Downloaded 66 images
Downloaded 67 images
Downloaded 68 images
Downloaded 69 images
Downloaded 70 images
Downloaded 71 images
Downloaded 72 images
Downloaded 73 images
Downloaded 74 images
Downloaded 75 images
Downloaded 76 images
Downloaded 77 images
Downloaded 78 images
Downloaded 79 images
Downloaded 80 images
Downloaded 81 images
Downloaded 82 images
Downloaded 83 images
Downloaded 84 images
Downloaded 85 images
Downloaded 86 images
Downloaded 87 images
Downloaded 88 images
Downloaded 89 images
Downloaded 90 images
Downloaded 91 images
Downloaded 92 images
Downloaded 93 images
Downloaded 94 images
Downloaded 95 images
Downloaded 96 images
Downloaded 97 images
Downloaded 98 images
Downloaded 99 images
Downloaded 100 images
Downloaded 101 images
Downloaded 102 images
Downloaded 103 images
Downloaded 104 images
Downloaded 105 images
Downloaded 106 images
Downloaded 107 images
Downloaded 108 images
Downloaded 109 images
Downloaded 110 images
Downloaded 111 images
Downloaded 112 images
Downloaded 113 images
Downloaded 114 images
Downloaded 115 images
Downloaded 116 images
Downloaded 117 images
Downloaded 118 images
Downloaded 119 images
Downloaded 120 images
Downloaded 121 images
Downloaded 122 images
Downloaded 123 images
Downloaded 124 images
Downloaded 125 images
Downloaded 126 images
Downloaded 127 images
Downloaded 128 images
Downloaded 129 images
Downloaded 130 images
Downloaded 131 images
Downloaded 132 images
Downloaded 133 images
Downloaded 134 images
Downloaded 135 images
Downloaded 136 images
Downloaded 137 images
Downloaded 138 images
Downloaded 139 images
Downloaded 140 images
Downloaded 141 images
Downloaded 142 images
Downloaded 143 images
Downloaded 144 images
Downloaded 145 images
Downloaded 146 images
Downloaded 147 images
Downloaded 148 images
Downloaded 149 images
Downloaded 150 images
Downloaded 151 images
Downloaded 152 images
Downloaded 153 images
Downloaded 154 images
Downloaded 155 images
Downloaded 156 images
Downloaded 157 images
Downloaded 158 images
Downloaded 159 images
Downloaded 160 images
Downloaded 161 images
Downloaded 162 images
Downloaded 163 images
Downloaded 164 images
Downloaded 165 images
Downloaded 166 images
Downloaded 167 images
Downloaded 168 images
Downloaded 169 images
Downloaded 170 images
Downloaded 171 images
Downloaded 172 images
Downloaded 173 images
Downloaded 174 images
Downloaded 175 images
Downloaded 176 images
Downloaded 177 images
Downloaded 178 images
Downloaded 179 images
Downloaded 180 images
Downloaded 181 images
Downloaded 182 images
Downloaded 183 images
Downloaded 184 images
Downloaded 185 images
Downloaded 186 images
Downloaded 187 images
Downloaded 188 images
Downloaded 189 images
Downloaded 190 images
Downloaded 191 images
Downloaded 192 images
Downloaded 193 images
Downloaded 194 images
Downloaded 195 images
Downloaded 196 images
Downloaded 197 images
Downloaded 198 images
Downloaded 199 images
Downloaded 200 images
Downloaded 201 images
Downloaded 202 images
Downloaded 203 images
Downloaded 204 images
Downloaded 205 images
Downloaded 206 images
Downloaded 207 images
Downloaded 208 images
Downloaded 209 images
Downloaded 210 images
Downloaded 211 images
Downloaded 212 images
Downloaded 213 images
Downloaded 214 images
Downloaded 215 images
Downloaded 216 images
Downloaded 217 images
Downloaded 218 images
Downloaded 219 images
Downloaded 220 images
Downloaded 221 images
Downloaded 222 images
Downloaded 223 images
Downloaded 224 images
Downloaded 225 images
Downloaded 226 images
Downloaded 227 images
Downloaded 228 images
Downloaded 229 images
Downloaded 230 images
Downloaded 231 images
Downloaded 232 images
Downloaded 233 images
Downloaded 234 images
Downloaded 235 images
Downloaded 236 images
Downloaded 237 images
Downloaded 238 images
Downloaded 239 images
Downloaded 240 images
Downloaded 241 images
Downloaded 242 images
Downloaded 243 images
Downloaded 244 images
Downloaded 245 images
Downloaded 246 images
Downloaded 247 images
Downloaded 248 images
Downloaded 249 images
Downloaded 250 images
Downloaded 251 images
Downloaded 252 images
Downloaded 253 images
Downloaded 254 images
Downloaded 255 images
Downloaded 256 images
Downloaded 257 images
Downloaded 258 images
Downloaded 259 images
Downloaded 260 images
Downloaded 261 images
Downloaded 262 images
Downloaded 263 images
Downloaded 264 images
Downloaded 265 images
Downloaded 266 images
Downloaded 267 images
Downloaded 268 images
Downloaded 269 images
Downloaded 270 images
Downloaded 271 images
Downloaded 272 images
Downloaded 273 images
Downloaded 274 images
Downloaded 275 images
Downloaded 276 images
Downloaded 277 images
Downloaded 278 images
Downloaded 279 images
Downloaded 280 images
Downloaded 281 images
Downloaded 282 images
Downloaded 283 images
Downloaded 284 images
Downloaded 285 images
Downloaded 286 images
Downloaded 287 images
Downloaded 288 images
Downloaded 289 images
Downloaded 290 images
Downloaded 291 images
Downloaded 292 images
Downloaded 293 images
Downloaded 294 images
Downloaded 295 images
Downloaded 296 images
Downloaded 297 images
Downloaded 298 images
Downloaded 299 images
Downloaded 300 images
Downloaded 301 images
Downloaded 302 images
Downloaded 303 images
Downloaded 304 images
Downloaded 305 images
Downloaded 306 images
Downloaded 307 images
Downloaded 308 images
Downloaded 309 images
Downloaded 310 images
Downloaded 311 images
Downloaded 312 images
Downloaded 313 images
Downloaded 314 images
Downloaded 315 images
Downloaded 316 images
Downloaded 317 images
Downloaded 318 images
Downloaded 319 images
Downloaded 320 images
Downloaded 321 images
Downloaded 322 images
Downloaded 323 images
Downloaded 324 images
Downloaded 325 images
Downloaded 326 images
Downloaded 327 images
Downloaded 328 images
Downloaded 329 images
Downloaded 330 images
Downloaded 331 images
Downloaded 332 images
Downloaded 333 images
Downloaded 334 images
Downloaded 335 images
Downloaded 336 images
Downloaded 337 images
Downloaded 338 images
Downloaded 339 images
Downloaded 340 images
Downloaded 341 images
Downloaded 342 images
Downloaded 343 images
Downloaded 344 images
Downloaded 345 images
Downloaded 346 images
Downloaded 347 images
Downloaded 348 images
Downloaded 349 images
Downloaded 350 images
Downloaded 351 images
Downloaded 352 images
Downloaded 353 images
Downloaded 354 images
Downloaded 355 images
Downloaded 356 images
Downloaded 357 images
Downloaded 358 images
Downloaded 359 images
Downloaded 360 images
Downloaded 361 images
Downloaded 362 images
Downloaded 363 images
Downloaded 364 images
Downloaded 365 images
Downloaded 366 images
Downloaded 367 images
Downloaded 368 images
Downloaded 369 images
Downloaded 370 images
Downloaded 371 images
Downloaded 372 images
Downloaded 373 images
Downloaded 374 images
Downloaded 375 images
Downloaded 376 images
Downloaded 377 images
Downloaded 378 images
Downloaded 379 images
Downloaded 380 images
Downloaded 381 images
Downloaded 382 images
Downloaded 383 images
Downloaded 384 images
Downloaded 385 images
Downloaded 386 images
Downloaded 387 images
Downloaded 388 images
Downloaded 389 images
Downloaded 390 images
Downloaded 391 images
Downloaded 392 images
Downloaded 393 images
Downloaded 394 images
Downloaded 395 images
Downloaded 396 images
Downloaded 397 images
Downloaded 398 images
Downloaded 399 images
Downloaded 400 images
Downloaded 401 images
Downloaded 402 images
Downloaded 403 images
Downloaded 404 images
Downloaded 405 images
Downloaded 406 images
Downloaded 407 images
Downloaded 408 images
Downloaded 409 images
Downloaded 410 images
Downloaded 411 images
Downloaded 412 images
Downloaded 413 images
Downloaded 414 images
Downloaded 415 images
Downloaded 416 images
Downloaded 417 images
Downloaded 418 images
Downloaded 419 images
Downloaded 420 images
Downloaded 421 images
Downloaded 422 images
Downloaded 423 images
Downloaded 424 images
Downloaded 425 images
Downloaded 426 images
Downloaded 427 images
Downloaded 428 images
Downloaded 429 images
Downloaded 430 images
Downloaded 431 images
Downloaded 432 images
Downloaded 433 images
Downloaded 434 images
Downloaded 435 images
Downloaded 436 images
Downloaded 437 images
Downloaded 438 images
Downloaded 439 images
Downloaded 440 images
Downloaded 441 images
Downloaded 442 images
Downloaded 443 images
Downloaded 444 images
Downloaded 445 images
Downloaded 446 images
Downloaded 447 images
Downloaded 448 images
Downloaded 449 images
Downloaded 450 images
Downloaded 451 images
Downloaded 452 images
Downloaded 453 images
Downloaded 454 images
Downloaded 455 images
Downloaded 456 images
Downloaded 457 images
Downloaded 458 images
Downloaded 459 images
Downloaded 460 images
Downloaded 461 images
Downloaded 462 images
Downloaded 463 images
Downloaded 464 images
Downloaded 465 images
Downloaded 466 images
Downloaded 467 images
Downloaded 468 images
Downloaded 469 images
Downloaded 470 images
Downloaded 471 images
Downloaded 472 images
Downloaded 473 images
Downloaded 474 images
Downloaded 475 images
Downloaded 476 images
Downloaded 477 images
Downloaded 478 images
Downloaded 479 images
Downloaded 480 images
Downloaded 481 images
Downloaded 482 images
Downloaded 483 images
Downloaded 484 images
Downloaded 485 images
Downloaded 486 images
Downloaded 487 images
Downloaded 488 images
Downloaded 489 images
Downloaded 490 images
Downloaded 491 images
Downloaded 492 images
Downloaded 493 images
Downloaded 494 images
Downloaded 495 images
Downloaded 496 images
Downloaded 497 images
Downloaded 498 images
Downloaded 499 images
Downloaded 500 images
Downloaded 501 images
Downloaded 502 images
Downloaded 503 images
Downloaded 504 images
Downloaded 505 images
Downloaded 506 images
Downloaded 507 images
Downloaded 508 images
Downloaded 509 images
Downloaded 510 images
Downloaded 511 images
Downloaded 512 images
Downloaded 513 images
Downloaded 514 images
Downloaded 515 images
Downloaded 516 images
Downloaded 517 images
Downloaded 518 images
Downloaded 519 images
Downloaded 520 images
Downloaded 521 images
Downloaded 522 images
Downloaded 523 images
Downloaded 524 images
Downloaded 525 images
Downloaded 526 images
Downloaded 527 images
Downloaded 528 images
Downloaded 529 images
Downloaded 530 images
Downloaded 531 images
Downloaded 532 images
Downloaded 533 images
Downloaded 534 images
Downloaded 535 images
Downloaded 536 images
Downloaded 537 images
Downloaded 538 images
Downloaded 539 images
Downloaded 540 images
Downloaded 541 images
Downloaded 542 images
Downloaded 543 images
Downloaded 544 images
Downloaded 545 images
Downloaded 546 images
Downloaded 547 images
Downloaded 548 images
Downloaded 549 images
Downloaded 550 images
Downloaded 551 images
Downloaded 552 images
Downloaded 553 images
Downloaded 554 images
Downloaded 555 images
Downloaded 556 images
Downloaded 557 images
Downloaded 558 images
Downloaded 559 images
Downloaded 560 images
Downloaded 561 images
Downloaded 562 images
Downloaded 563 images
Downloaded 564 images
Downloaded 565 images
Downloaded 566 images
Downloaded 567 images
Downloaded 568 images
Downloaded 569 images
Downloaded 570 images
Downloaded 571 images
Downloaded 572 images
Downloaded 573 images
Downloaded 574 images
Downloaded 575 images
Downloaded 576 images
Downloaded 577 images
Downloaded 578 images
Downloaded 579 images
Downloaded 580 images
Downloaded 581 images
Downloaded 582 images
Downloaded 583 images
Downloaded 584 images
Downloaded 585 images
Downloaded 586 images
Downloaded 587 images
Downloaded 588 images
Downloaded 589 images
Downloaded 590 images
Downloaded 591 images
Downloaded 592 images
Downloaded 593 images
Downloaded 594 images
Downloaded 595 images
Downloaded 596 images
Downloaded 597 images
Downloaded 598 images
Downloaded 599 images
Downloaded 600 images
Downloaded 601 images
Downloaded 602 images
Downloaded 603 images
Downloaded 604 images
Downloaded 605 images
Downloaded 606 images
Downloaded 607 images
Downloaded 608 images
Downloaded 609 images
Downloaded 610 images
Downloaded 611 images
Downloaded 612 images
Downloaded 613 images
Downloaded 614 images
Downloaded 615 images
Downloaded 616 images
Downloaded 617 images
Downloaded 618 images
Downloaded 619 images
Downloaded 620 images
Downloaded 621 images
Downloaded 622 images
Downloaded 623 images
Downloaded 624 images
Downloaded 625 images
Downloaded 626 images
Downloaded 627 images
Downloaded 628 images
Downloaded 629 images
Downloaded 630 images
Downloaded 631 images
Downloaded 632 images
Downloaded 633 images
Downloaded 634 images
Downloaded 635 images
Downloaded 636 images
Downloaded 637 images
Downloaded 638 images
Downloaded 639 images
Downloaded 640 images
Downloaded 641 images
Downloaded 642 images
Downloaded 643 images
Downloaded 644 images
Downloaded 645 images
Downloaded 646 images
Downloaded 647 images
Downloaded 648 images
Downloaded 649 images
Downloaded 650 images
Downloaded 651 images
Downloaded 652 images
Downloaded 653 images
Downloaded 654 images
Downloaded 655 images
Downloaded 656 images
Downloaded 657 images
Downloaded 658 images
Downloaded 659 images
Downloaded 660 images
Downloaded 661 images
Downloaded 662 images
Downloaded 663 images
Downloaded 664 images
Downloaded 665 images
Downloaded 666 images
Downloaded 667 images
Downloaded 668 images
Downloaded 669 images
Downloaded 670 images
Downloaded 671 images
Downloaded 672 images
Downloaded 673 images
Downloaded 674 images
Downloaded 675 images
Downloaded 676 images
Downloaded 677 images
Downloaded 678 images
Downloaded 679 images
Downloaded 680 images
Downloaded 681 images
Downloaded 682 images
Downloaded 683 images
Downloaded 684 images
Downloaded 685 images
Downloaded 686 images
Downloaded 687 images
Downloaded 688 images
Downloaded 689 images
Downloaded 690 images
Downloaded 691 images
Downloaded 692 images
Downloaded 693 images
Downloaded 694 images
Downloaded 695 images
Downloaded 696 images
Downloaded 697 images
Downloaded 698 images
Downloaded 699 images
Downloaded 700 images
Downloaded 701 images
Downloaded 702 images
Downloaded 703 images
Downloaded 704 images
Downloaded 705 images
Downloaded 706 images
Downloaded 707 images
Downloaded 708 images
Downloaded 709 images
Downloaded 710 images
Downloaded 711 images
Downloaded 712 images
Downloaded 713 images
Downloaded 714 images
Downloaded 715 images
Downloaded 716 images
Downloaded 717 images
Downloaded 718 images
Downloaded 719 images
Downloaded 720 images
Downloaded 721 images
Downloaded 722 images
Downloaded 723 images
Downloaded 724 images
Downloaded 725 images
Downloaded 726 images
Downloaded 727 images
Downloaded 728 images
Downloaded 729 images
Downloaded 730 images
Downloaded 731 images
Downloaded 732 images
Downloaded 733 images
Downloaded 734 images
Downloaded 735 images
Downloaded 736 images
Downloaded 737 images
Downloaded 738 images
Downloaded 739 images
Downloaded 740 images
Downloaded 741 images
Downloaded 742 images
Downloaded 743 images
Downloaded 744 images
Downloaded 745 images
Downloaded 746 images
Downloaded 747 images
Downloaded 748 images
Downloaded 749 images
Downloaded 750 images
Downloaded 751 images
Downloaded 752 images
Downloaded 753 images
Downloaded 754 images
Downloaded 755 images
Downloaded 756 images
Downloaded 757 images
Downloaded 758 images
Downloaded 759 images
Downloaded 760 images
Downloaded 761 images
Downloaded 762 images
Downloaded 763 images
Downloaded 764 images
Downloaded 765 images
Downloaded 766 images
Downloaded 767 images
Downloaded 768 images
Downloaded 769 images
Downloaded 770 images
Downloaded 771 images
Downloaded 772 images
Downloaded 773 images
Downloaded 774 images
Downloaded 775 images
Downloaded 776 images
Downloaded 777 images
Downloaded 778 images
Downloaded 779 images
Downloaded 780 images
Downloaded 781 images
Downloaded 782 images
Downloaded 783 images
Downloaded 784 images
Downloaded 785 images
Downloaded 786 images
Downloaded 787 images
Downloaded 788 images
Downloaded 789 images
Downloaded 790 images
Downloaded 791 images
Downloaded 792 images
Downloaded 793 images
Downloaded 794 images
Downloaded 795 images
Downloaded 796 images
Downloaded 797 images
Downloaded 798 images
Downloaded 799 images
Downloaded 800 images
Downloaded 801 images
Downloaded 802 images
Downloaded 803 images
Downloaded 804 images
Downloaded 805 images
Downloaded 806 images
Downloaded 807 images
Downloaded 808 images
Downloaded 809 images
Downloaded 810 images
Downloaded 811 images
Downloaded 812 images
Downloaded 813 images
Downloaded 814 images
Downloaded 815 images
Downloaded 816 images
Downloaded 817 images
Downloaded 818 images
Downloaded 819 images
Downloaded 820 images
Downloaded 821 images
Downloaded 822 images
Downloaded 823 images
Downloaded 824 images
Downloaded 825 images
Downloaded 826 images
Downloaded 827 images
Downloaded 828 images
Downloaded 829 images
Downloaded 830 images
Downloaded 831 images
Downloaded 832 images
Downloaded 833 images
Downloaded 834 images
Downloaded 835 images
Downloaded 836 images
Downloaded 837 images
Downloaded 838 images
Downloaded 839 images
Downloaded 840 images
Downloaded 841 images
Downloaded 842 images
Downloaded 843 images
Downloaded 844 images
Downloaded 845 images
Downloaded 846 images
Downloaded 847 images
Downloaded 848 images
Downloaded 849 images
Downloaded 850 images
Downloaded 851 images
Downloaded 852 images
Downloaded 853 images
Downloaded 854 images
Downloaded 855 images
Downloaded 856 images
Downloaded 857 images
Downloaded 858 images
Downloaded 859 images
Downloaded 860 images
Downloaded 861 images
Downloaded 862 images
Downloaded 863 images
Downloaded 864 images
Downloaded 865 images
Downloaded 866 images
Downloaded 867 images
Downloaded 868 images
Downloaded 869 images
Downloaded 870 images
Downloaded 871 images
Downloaded 872 images
Downloaded 873 images
Downloaded 874 images
Downloaded 875 images
Downloaded 876 images
Downloaded 877 images
Downloaded 878 images
Downloaded 879 images
Downloaded 880 images
Downloaded 881 images
Downloaded 882 images
Downloaded 883 images
Downloaded 884 images
Downloaded 885 images
Downloaded 886 images
Downloaded 887 images
Downloaded 888 images
Downloaded 889 images
Downloaded 890 images
Downloaded 891 images
Downloaded 892 images
Downloaded 893 images
Downloaded 894 images
Downloaded 895 images
Downloaded 896 images
Downloaded 897 images
Downloaded 898 images
Downloaded 899 images
Downloaded 900 images
Downloaded 901 images
Downloaded 902 images
Downloaded 903 images
Downloaded 904 images
Downloaded 905 images
Downloaded 906 images
Downloaded 907 images
Downloaded 908 images
Downloaded 909 images
Downloaded 910 images
Downloaded 911 images
Downloaded 912 images
Downloaded 913 images
Downloaded 914 images

In [5]:
# Combine sample products and csv
images_df = pd.read_csv('/notebooks/images/images.csv')

# Merge DataFrames on the 'id' column
merged_df = pd.merge(df, images_df, on='id', how='inner')

In [6]:
# view data
pd.set_option('display.max_colwidth', None)

merged_df

,Unnamed: 0,id,product title,image_url,price,image_name
0,0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black, Checked-Large 29-Inch",https://m.media-amazon.com/images/I/815dLQKYIYL._AC_UL320_.jpg,139.99,B014TMV5YE.jpg
1,1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcase Double Wheels TSA Lock Blue,https://m.media-amazon.com/images/I/81bQlm7vf6L._AC_UL320_.jpg,169.99,B07GDLCQXV.jpg
2,2,B07XSCCZYG,"Platinum Elite Softside Expandable Checked Luggage, 8 Wheel Spinner Suitcase, TSA Lock, Men and Women, True Navy Blue, Checked Medium 25-Inch",https://m.media-amazon.com/images/I/71EA35zvJBL._AC_UL320_.jpg,365.49,B07XSCCZYG.jpg
3,3,B08MVFKGJM,"Freeform Hardside Expandable with Double Spinner Wheels, Navy, 2-Piece Set (21/28)",https://m.media-amazon.com/images/I/91k6NYLQyIL._AC_UL320_.jpg,291.59,B08MVFKGJM.jpg
4,4,B01DJLKZBA,"Winfield 2 Hardside Expandable Luggage with Spinner Wheels, Checked-Large 28-Inch, Deep Blue",https://m.media-amazon.com/images/I/61NJoaZcP9L._AC_UL320_.jpg,174.99,B01DJLKZBA.jpg
...,...,...,...,...,...,...
9991,9995,B0BR617B8P,Mens Athletic Workout Shorts with Compression Liner 7 inch Inseam,https://m.media-amazon.com/images/I/61MFjWYxa5L._AC_UL320_.jpg,34.99,B0BR617B8P.jpg
9992,9996,B07VWSP5HD,Men's Knitted Regular Fit Full Zip Cardigan Sweater with Soft Brushed Flannel Lining,https://m.media-amazon.com/images/I/91Hm4RVlu8L._AC_UL320_.jpg,49.99,B07VWSP5HD.jpg
9993,9997,B0CD6MBV8T,Men's Jacket Windproof Qulited Bomber Jackets Casual Fall Winter Warm Padded Coats Outwear,https://m.media-amazon.com/images/I/61sVoWGbg3L._AC_UL320_.jpg,46.98,B0CD6MBV8T.jpg
9994,9998,B08XW98F22,Men's Dry Franchise Polo,https://m.media-amazon.com/images/I/51yJ8ZYPcsL._AC_UL320_.jpg,46.87,B08XW98F22.jpg
9995,9999,B077SN37K5,"Men’s Athletic Sock 8-pair, White (White, 13+)",https://m.media-amazon.com/images/I/61R4-uAH97L._AC_UL320_.jpg,0.00,B077SN37K5.jpg

In [7]:
merged_df.to_csv('merged_data_myself.csv', index=False)

In [8]:
merged_df.drop(columns=['Unnamed: 0'], inplace=True)

In [9]:
merged_df.drop(columns=['id', 'product title', 'image_url'], inplace=True)

In [10]:
merged_df

       price      image_name
0     139.99  B014TMV5YE.jpg
1     169.99  B07GDLCQXV.jpg
2     365.49  B07XSCCZYG.jpg
3     291.59  B08MVFKGJM.jpg
4     174.99  B01DJLKZBA.jpg
...      ...             ...
9991   34.99  B0BR617B8P.jpg
9992   49.99  B07VWSP5HD.jpg
9993   46.98  B0CD6MBV8T.jpg
9994   46.87  B08XW98F22.jpg
9995    0.00  B077SN37K5.jpg

[9996 rows x 2 columns]

In [11]:
for i, row in merged_df.iterrows():
    if row['price'] == 0.00:
        merged_df.drop(i, inplace=True)

In [13]:
merged_df

       price      image_name
0     139.99  B014TMV5YE.jpg
1     169.99  B07GDLCQXV.jpg
2     365.49  B07XSCCZYG.jpg
3     291.59  B08MVFKGJM.jpg
4     174.99  B01DJLKZBA.jpg
...      ...             ...
9990  209.50  B09V11RVFC.jpg
9991   34.99  B0BR617B8P.jpg
9992   49.99  B07VWSP5HD.jpg
9993   46.98  B0CD6MBV8T.jpg
9994   46.87  B08XW98F22.jpg

[9814 rows x 2 columns]

In [30]:
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import SGD

In [31]:
# Load your dataset (assuming it's in a DataFrame format)
df = merged_df

In [32]:
# Split dataset into train and test sets
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

In [33]:
# Set up ImageDataGenerator for loading images
datagen = ImageDataGenerator(rescale=1./255)  # Scale pixel values to [0, 1]

In [34]:
# Define image size
img_size = (224, 224)  # VGG16 input size

In [35]:
# Load and preprocess images using the ImageDataGenerator
train_generator = datagen.flow_from_dataframe(
    dataframe=train_df,
    directory='/notebooks/images',
    x_col='image_name',  # Assuming 'image_name' column contains file names
    y_col='price',  # Assuming 'price' column contains continuous labels
    target_size=img_size,
    batch_size=32,
    class_mode='raw'  # Use 'raw' for regression
)

test_generator = datagen.flow_from_dataframe(
    dataframe=test_df,
    directory='/notebooks/images',
    x_col='image_name',
    y_col='price',
    target_size=img_size,
    batch_size=32,
    class_mode='raw'
)

Found 7851 validated image filenames.
Found 1963 validated image filenames.

In [36]:
# Load pre-trained VGG16 model
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# Freeze the convolutional base
base_model.trainable = False

# Create a new model on top
model = Sequential([
    base_model,
    Flatten(),
    Dense(256, activation='relu'),
    Dense(1)  # Output layer with a single neuron for regression
])

In [37]:
# Compile the model
model.compile(optimizer=SGD(lr=0.001), loss='mean_squared_error', metrics=['mae'])

/usr/local/lib/python3.9/dist-packages/keras/optimizers/optimizer_v2/gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)

In [38]:
# Train the model
model.fit(train_generator, epochs=10, validation_data=test_generator)

Epoch 1/10
246/246 [==============================] - 64s 234ms/step - loss: 26365.3867 - mae: 60.2322 - val_loss: 7849.3101 - val_mae: 40.4084
Epoch 2/10
246/246 [==============================] - 47s 191ms/step - loss: 5601.6841 - mae: 32.2409 - val_loss: 6914.7139 - val_mae: 33.0640
Epoch 3/10
246/246 [==============================] - 37s 150ms/step - loss: 5062.9951 - mae: 29.8682 - val_loss: 6539.5859 - val_mae: 33.5078
Epoch 4/10
246/246 [==============================] - 32s 131ms/step - loss: 4863.3945 - mae: 31.2758 - val_loss: 6389.0010 - val_mae: 35.1351
Epoch 5/10
246/246 [==============================] - 33s 132ms/step - loss: 4788.8813 - mae: 32.8303 - val_loss: 6323.3623 - val_mae: 36.4195
Epoch 6/10
246/246 [==============================] - 33s 132ms/step - loss: 4761.2969 - mae: 33.9731 - val_loss: 6294.8149 - val_mae: 37.2443
Epoch 7/10
246/246 [==============================] - 32s 131ms/step - loss: 4751.0747 - mae: 34.6490 - val_loss: 6280.8447 - val_mae: 37.7709
Epoch 8/10
246/246 [==============================] - 32s 131ms/step - loss: 4747.0806 - mae: 35.0745 - val_loss: 6273.7280 - val_mae: 38.0926
Epoch 9/10
246/246 [==============================] - 32s 131ms/step - loss: 4745.6528 - mae: 35.4097 - val_loss: 6269.6665 - val_mae: 38.3238
Epoch 10/10
246/246 [==============================] - 32s 131ms/step - loss: 4745.1108 - mae: 35.5366 - val_loss: 6267.4688 - val_mae: 38.4563

# ResNet50

In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import SGD

# Load your dataset (assuming it's in a DataFrame format)
df = merged_df

# Split dataset into train and test sets
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

# Set up ImageDataGenerator for loading images
datagen = ImageDataGenerator(rescale=1./255)  # Scale pixel values to [0, 1]

# Define image size
img_size = (224, 224)  # ResNet50 input size

# Load and preprocess images using the ImageDataGenerator
train_generator = datagen.flow_from_dataframe(
    dataframe=train_df,
    directory='/notebooks/images',
    x_col='image_name',  # Assuming 'image_name' column contains file names
    y_col='price',  # Assuming 'price' column contains continuous labels
    target_size=img_size,
    batch_size=32,
    class_mode='raw'  # Use 'raw' for regression
)

test_generator = datagen.flow_from_dataframe(
    dataframe=test_df,
    directory='/notebooks/images',
    x_col='image_name',
    y_col='price',
    target_size=img_size,
    batch_size=32,
    class_mode='raw'
)

# Load pre-trained ResNet50 model
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# Freeze the convolutional base
base_model.trainable = False

# Create a new model on top
model = Sequential([
    base_model,
    Flatten(),
    Dense(256, activation='relu'),
    Dense(1)  # Output layer with a single neuron for regression
])

# Compile the model
model.compile(optimizer=SGD(lr=0.001), loss='mean_squared_error', metrics=['mae'])

# Train the model
model.fit(train_generator, epochs=20, validation_data=test_generator)

Found 7851 validated image filenames.
Found 1963 validated image filenames.

/usr/local/lib/python3.9/dist-packages/keras/optimizers/optimizer_v2/gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)

Epoch 1/20
110/246 [============>.................] - ETA: 47s - loss: nan - mae: nan

KeyboardInterrupt:

# without image rescale

In [3]:
pip install ultralytics==8.0.196

Collecting ultralytics==8.0.196
  Downloading ultralytics-8.0.196-py3-none-any.whl (631 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 631.1/631.1 kB 38.1 MB/s eta 0:00:00
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.9/dist-packages (from ultralytics==8.0.196) (5.4.1)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.9/dist-packages (from ultralytics==8.0.196) (1.12.1+cu116)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.9/dist-packages (from ultralytics==8.0.196) (9.2.0)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.9/dist-packages (from ultralytics==8.0.196) (1.12.0)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.9/dist-packages (from ultralytics==8.0.196) (0.13.1+cu116)
Collecting py-cpuinfo
  Downloading py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
Collecting thop>=0.1.1
  Downloading thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.9/dist-packages (from ultralytics==8.0.196) (2.28.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.9/dist-packages (from ultralytics==8.0.196) (5.9.4)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.9/dist-packages (from ultralytics==8.0.196) (4.64.1)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.9/dist-packages (from ultralytics==8.0.196) (1.5.0)
Requirement already satisfied: seaborn>=0.11.0 in /usr/local/lib/python3.9/dist-packages (from ultralytics==8.0.196) (0.12.0)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.9/dist-packages (from ultralytics==8.0.196) (4.6.0.66)
Requirement already satisfied: numpy>=1.22.2 in /usr/local/lib/python3.9/dist-packages (from ultralytics==8.0.196) (1.23.4)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.9/dist-packages (from ultralytics==8.0.196) (3.6.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.0->ultralytics==8.0.196) (1.0.7)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.0->ultralytics==8.0.196) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.0->ultralytics==8.0.196) (4.38.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.0->ultralytics==8.0.196) (0.10.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.0->ultralytics==8.0.196) (3.0.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.0->ultralytics==8.0.196) (23.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib>=3.3.0->ultralytics==8.0.196) (1.4.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.1.4->ultralytics==8.0.196) (2022.7.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.23.0->ultralytics==8.0.196) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests>=2.23.0->ultralytics==8.0.196) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.23.0->ultralytics==8.0.196) (2023.7.22)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests>=2.23.0->ultralytics==8.0.196) (2.1.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/dist-packages (from torch>=1.8.0->ultralytics==8.0.196) (4.4.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from cycler>=0.10->matplotlib>=3.3.0->ultralytics==8.0.196) (1.14.0)
Installing collected packages: py-cpuinfo, thop, ultralytics
Successfully installed py-cpuinfo-9.0.0 thop-0.1.1.post2209072238 ultralytics-8.0.196
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.

In [1]:
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="cbvlBgaQv3TtG6UGBXbL")
project = rf.workspace("objectdetecttrade").project("fxtb")
dataset = project.version(661).download("yolov8")

Requirement already satisfied: roboflow in /usr/local/lib/python3.9/dist-packages (1.1.19)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.9/dist-packages (from roboflow) (1.0.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.9/dist-packages (from roboflow) (2.8.2)
Requirement already satisfied: idna==2.10 in /usr/local/lib/python3.9/dist-packages (from roboflow) (2.10)
Requirement already satisfied: supervision in /usr/local/lib/python3.9/dist-packages (from roboflow) (0.18.0)
Requirement already satisfied: certifi==2023.7.22 in /usr/local/lib/python3.9/dist-packages (from roboflow) (2023.7.22)
Requirement already satisfied: chardet==4.0.0 in /usr/local/lib/python3.9/dist-packages (from roboflow) (4.0.0)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from roboflow) (2.28.2)
Requirement already satisfied: opencv-python-headless==4.8.0.74 in /usr/local/lib/python3.9/dist-packages (from roboflow) (4.8.0.74)
Requirement already satisfied: tqdm>=4.41.0 in /usr/local/lib/python3.9/dist-packages (from roboflow) (4.64.1)
Requirement already satisfied: urllib3>=1.26.6 in /usr/local/lib/python3.9/dist-packages (from roboflow) (1.26.14)
Requirement already satisfied: requests-toolbelt in /usr/local/lib/python3.9/dist-packages (from roboflow) (0.10.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.9/dist-packages (from roboflow) (1.4.4)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.9/dist-packages (from roboflow) (3.6.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from roboflow) (1.14.0)
Requirement already satisfied: cycler==0.10.0 in /usr/local/lib/python3.9/dist-packages (from roboflow) (0.10.0)
Requirement already satisfied: Pillow>=7.1.2 in /usr/local/lib/python3.9/dist-packages (from roboflow) (9.2.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.9/dist-packages (from roboflow) (1.23.4)
Requirement already satisfied: python-magic in /usr/local/lib/python3.9/dist-packages (from roboflow) (0.4.27)
Requirement already satisfied: PyYAML>=5.3.1 in /usr/local/lib/python3.9/dist-packages (from roboflow) (5.4.1)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->roboflow) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->roboflow) (1.0.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->roboflow) (23.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->roboflow) (4.38.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests->roboflow) (2.1.1)
Requirement already satisfied: scipy<2.0.0,>=1.10.0 in /usr/local/lib/python3.9/dist-packages (from supervision->roboflow) (1.12.0)
Requirement already satisfied: defusedxml<0.8.0,>=0.7.1 in /usr/local/lib/python3.9/dist-packages (from supervision->roboflow) (0.7.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
loading Roboflow workspace...
loading Roboflow project...

transfer learning (BCNet)
models (3E-Net)
EfficientNetB0
EfficientNetV2B0
EfficientNetV2B0-21k
ResNetV1-50
ResNetV2-50
MobileNetV1
MobileNetV2

additionally, search CNN in paperswithcode

https://paperswithcode.com/paper/libra-r-cnn-towards-balanced-learning-for

https://paperswithcode.com/paper/cascade-r-cnn-delving-into-high-quality

https://paperswithcode.com/paper/dynamic-r-cnn-towards-high-quality-object

https://paperswithcode.com/paper/mask-r-cnn

https://paperswithcode.com/paper/grid-r-cnn